%%{init: { 
'themeVariables': {
			'cScale0': '#a6d189', 'cScaleLabel0': '#000',
			'cScale1': '#dc8a78','cScaleLabel1': '#000',
			'cScale2': '#81c8be','cScaleLabel2': '#000',
			"fontFamily": "Roboto"
		} }
}%%

timeline
	Paradigma : Período de ciencia normal
				: Se recopilan datos y hacen experimentos
				: Se ajusta la teoría
				: Se postergan las anomalías
	Crisis  : Aparece un evento no explicado y apremiante (anomalía)
			: Se proponen muchas teorias candidatas
			: Se asienta alguna de las teorías candidatas (revolución)
	Paradigma : Período de ciencia normal
				: ...