flowchart LR
   
    A[Diferencias lingüísticas] --> B[Diferencias conceptuales]
    B -- Ciencias Sociales --> C[Diferencias ontológicas]

    B --> D[Diferencias en Construcción Psicológica]

    D --> C

